// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_image: dynamic(() => import("./BlogImage")),
  paragraph: dynamic(() => import("./Paragraph")),
  paragraph_title: dynamic(() => import("./ParagraphTitle")),
  quote: dynamic(() => import("./Quote")),
};
